In [2]:
#Sort, Search & Counting Functions.

In [3]:
import numpy as np

In [5]:
arr = np.random.randint(1,70 , 8)

In [9]:
arr

array([ 1, 18, 11, 39, 46, 40, 14, 11])

In [10]:
np.sort(arr)

array([ 1, 11, 11, 14, 18, 39, 40, 46])

In [11]:
np.searchsorted(arr, 34)

3

In [17]:
arr1 = np.array([0,325,452,0,0,0,0])

In [18]:
np.where(arr>6)

(array([1, 2, 3, 4, 5, 6, 7]),)

In [19]:
arr

array([ 1, 18, 11, 39, 46, 40, 14, 11])

In [20]:
np.extract(arr>3, arr)

array([18, 11, 39, 46, 40, 14, 11])

In [21]:
# Numpy - Byte Swapping

In [22]:
arr.byteswap()

array([  72057594037927936, 1297036692682702848,  792633534417207296,
       2810246167479189504, 3314649325744685056, 2882303761517117440,
       1008806316530991104,  792633534417207296])

In [23]:
a = np.copy(arr)

In [24]:
a

array([ 1, 18, 11, 39, 46, 40, 14, 11])

In [25]:
b = arr.view()

In [26]:
b

array([ 1, 18, 11, 39, 46, 40, 14, 11])

In [27]:
arr

array([ 1, 18, 11, 39, 46, 40, 14, 11])

In [28]:
b[0]

1

In [29]:
#Numpy - Matrix Library.

In [31]:
import numpy.matlib as nm

In [32]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [33]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [35]:
#Numpy - Linear Algebra

In [36]:
arr1 = np.random.randint([[2,3],[4,5]])

In [37]:
arr2 = np.random.randint([[2,3],[4,5]])

In [38]:
np.dot(arr1,arr2)

array([[ 0,  0],
       [ 0, 12]])

In [39]:
arr1@arr2

array([[ 0,  0],
       [ 0, 12]])