In [23]:
#Numpy - Array Manipulation.

In [24]:
import numpy as np

In [25]:
arr = np.random.randint(1,10 , (3,4))

In [26]:
arr

array([[4, 2, 7, 3],
       [4, 8, 9, 8],
       [5, 5, 9, 7]])

In [27]:
arr.reshape(6,2)

array([[4, 2],
       [7, 3],
       [4, 8],
       [9, 8],
       [5, 5],
       [9, 7]])

In [28]:
arr.reshape(2,6)

array([[4, 2, 7, 3, 4, 8],
       [9, 8, 5, 5, 9, 7]])

In [29]:
arr.T

array([[4, 4, 5],
       [2, 8, 5],
       [7, 9, 9],
       [3, 8, 7]])

In [30]:
arr.flatten()

array([4, 2, 7, 3, 4, 8, 9, 8, 5, 5, 9, 7])

In [31]:
arr1 = np.array([1,2,3,4,5])

In [32]:
arr1.ndim

1

In [33]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
arr

array([[4, 2, 7, 3],
       [4, 8, 9, 8],
       [5, 5, 9, 7]])

In [35]:
np.squeeze(arr)

array([[4, 2, 7, 3],
       [4, 8, 9, 8],
       [5, 5, 9, 7]])

In [36]:
data = np.array([[1] , [2] , [3]])

In [37]:
data

array([[1],
       [2],
       [3]])

In [38]:
np.squeeze(data)

array([1, 2, 3])

In [39]:
arr1

array([1, 2, 3, 4, 5])

In [40]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [42]:
np.roll(arr1 , 2)

array([4, 5, 1, 2, 3])

In [44]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
#Numpy - Binary Operators.

In [46]:
arr1 = np.random.randint(1,10 , (3,4))

In [48]:
arr2 = np.random.randint(1,10 , (3,4))

In [47]:
arr1

array([[1, 7, 9, 7],
       [9, 3, 4, 1],
       [2, 2, 8, 1]])

In [49]:
arr2

array([[3, 9, 4, 5],
       [6, 1, 5, 8],
       [8, 6, 9, 4]])

In [50]:
arr1+arr2

array([[ 4, 16, 13, 12],
       [15,  4,  9,  9],
       [10,  8, 17,  5]])

In [51]:
arr1*arr2

array([[ 3, 63, 36, 35],
       [54,  3, 20,  8],
       [16, 12, 72,  4]])

In [52]:
arr1/arr2

array([[0.33333333, 0.77777778, 2.25      , 1.4       ],
       [1.5       , 3.        , 0.8       , 0.125     ],
       [0.25      , 0.33333333, 0.88888889, 0.25      ]])

In [53]:
arr1-arr2

array([[-2, -2,  5,  2],
       [ 3,  2, -1, -7],
       [-6, -4, -1, -3]])

In [55]:
arr1%arr2

array([[1, 7, 1, 2],
       [3, 0, 4, 1],
       [2, 2, 8, 1]])

In [56]:
arr1**arr2

array([[        1,  40353607,      6561,     16807],
       [   531441,         3,      1024,         1],
       [      256,        64, 134217728,         1]])

In [57]:
arr1&arr2

array([[1, 1, 0, 5],
       [0, 1, 4, 0],
       [0, 2, 8, 0]])

In [58]:
~arr1

array([[ -2,  -8, -10,  -8],
       [-10,  -4,  -5,  -2],
       [ -3,  -3,  -9,  -2]])

In [59]:
arr1|arr2

array([[ 3, 15, 13,  7],
       [15,  3,  5,  9],
       [10,  6,  9,  5]])

In [60]:
arr1>arr2

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [61]:
arr1<arr2

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
arr1==arr2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [63]:
#Numpy - String Function

In [65]:
arr = np.array(['ganesh','gadkari'])

In [66]:
arr

array(['ganesh', 'gadkari'], dtype='<U7')

In [67]:
np.char.upper(arr)

array(['GANESH', 'GADKARI'], dtype='<U7')

In [69]:
np.char.title(arr)

array(['Ganesh', 'Gadkari'], dtype='<U7')

In [70]:
np.char.capitalize(arr)

array(['Ganesh', 'Gadkari'], dtype='<U7')

In [71]:
#Numpy Matahamatical Functions.

In [72]:
arr1

array([[1, 7, 9, 7],
       [9, 3, 4, 1],
       [2, 2, 8, 1]])

In [73]:
np.sin(arr1)

array([[ 0.84147098,  0.6569866 ,  0.41211849,  0.6569866 ],
       [ 0.41211849,  0.14112001, -0.7568025 ,  0.84147098],
       [ 0.90929743,  0.90929743,  0.98935825,  0.84147098]])

In [74]:
np.cos(arr1)

array([[ 0.54030231,  0.75390225, -0.91113026,  0.75390225],
       [-0.91113026, -0.9899925 , -0.65364362,  0.54030231],
       [-0.41614684, -0.41614684, -0.14550003,  0.54030231]])

In [75]:
np.tan(arr1)

array([[ 1.55740772,  0.87144798, -0.45231566,  0.87144798],
       [-0.45231566, -0.14254654,  1.15782128,  1.55740772],
       [-2.18503986, -2.18503986, -6.79971146,  1.55740772]])

In [76]:
np.tanh(arr1)

array([[0.76159416, 0.99999834, 0.99999997, 0.99999834],
       [0.99999997, 0.99505475, 0.9993293 , 0.76159416],
       [0.96402758, 0.96402758, 0.99999977, 0.76159416]])

In [77]:
np.log10(arr1)

array([[0.        , 0.84509804, 0.95424251, 0.84509804],
       [0.95424251, 0.47712125, 0.60205999, 0.        ],
       [0.30103   , 0.30103   , 0.90308999, 0.        ]])

In [78]:
np.exp(arr1)

array([[2.71828183e+00, 1.09663316e+03, 8.10308393e+03, 1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 5.45981500e+01, 2.71828183e+00],
       [7.38905610e+00, 7.38905610e+00, 2.98095799e+03, 2.71828183e+00]])

In [79]:
np.sqrt(arr1)

array([[1.        , 2.64575131, 3.        , 2.64575131],
       [3.        , 1.73205081, 2.        , 1.        ],
       [1.41421356, 1.41421356, 2.82842712, 1.        ]])

In [81]:
np.power(arr1,2)

array([[ 1, 49, 81, 49],
       [81,  9, 16,  1],
       [ 4,  4, 64,  1]])

In [82]:
np.mean(arr1)

4.5

In [83]:
np.median(arr1)

3.5

In [86]:
np.std(arr1)

3.122498999199199

In [87]:
np.var(arr1)

9.75

In [88]:
np.min(arr1)

1

In [90]:
np.max(arr1)

9