In [55]:
import numpy as np

In [56]:
l = [1,2,3,4]

In [57]:
ar = np.array(l)

In [58]:
ar

array([1, 2, 3, 4])

In [59]:
type(ar)

numpy.ndarray

In [60]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [61]:
np.asarray(l)

array([1, 2, 3, 4])

In [62]:
a = [2,3,4]

In [63]:
np.asanyarray(a)

array([2, 3, 4])

In [64]:
b = np.matrix(l)

In [65]:
b

matrix([[1, 2, 3, 4]])

In [66]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [67]:
a = np.array(l)

In [68]:
a

array([1, 2, 3, 4])

In [69]:
c = a

In [70]:
c

array([1, 2, 3, 4])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
c[0] = 100

In [73]:
c

array([100,   2,   3,   4])

In [74]:
a

array([100,   2,   3,   4])

In [75]:
d = np.copy(a)

In [76]:
d

array([100,   2,   3,   4])

In [77]:
a

array([100,   2,   3,   4])

In [78]:
a[1] = 400

In [79]:
a

array([100, 400,   3,   4])

In [80]:
d

array([100,   2,   3,   4])

In [81]:
np.fromfunction(lambda i ,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [82]:
np.fromfunction(lambda i ,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [83]:
iterable = (i*i for i in range(5))

In [84]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [85]:
np.fromstring("234 453", sep = " ")

array([234., 453.])

In [86]:
np.fromstring("4,5", sep = ",")

array([4., 5.])

In [87]:
# numpy data types

In [88]:
l = [2,3,4,5,6]

In [89]:
ar = np.array(l)

In [90]:
ar

array([2, 3, 4, 5, 6])

In [91]:
ar.ndim

1

In [92]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [93]:
ar2.ndim

2

In [94]:
ar2.size

8

In [95]:
ar.shape 

(5,)

In [96]:
ar2.shape

(2, 4)

In [97]:
ar.dtype

dtype('int64')

In [98]:
ar2.dtype

dtype('int64')

In [99]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [100]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [101]:
ar22.dtype

dtype('float64')

In [102]:
list(range(5))

[0, 1, 2, 3, 4]

In [103]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [104]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [105]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [106]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [110]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [111]:
np.ones(3)

array([1., 1., 1.])

In [112]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [115]:
on = np.ones((2,3,4))

In [116]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [117]:
on + 5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [118]:
np.empty((3,5))

array([[4.68623254e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [119]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [120]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [124]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [125]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [126]:
np.logspace(2,5,10,base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [129]:
arr = np.random.randn(3,4)

In [130]:
import pandas as pd

In [131]:
pd.DataFrame(arr)

0         1         2         3
0 -0.780551 -0.527984 -0.587431  0.680141
1  0.021562 -0.800330 -1.322127  0.742462
2 -0.753619  0.544708 -1.080250  0.468291

In [138]:
arr = np.random.rand(3,4)

In [139]:
pd.DataFrame(np.random.randint(1,110,(3,4))).to_csv('test.csv')

In [140]:
arr

array([[0.85086192, 0.5041171 , 0.66829838, 0.43191059],
       [0.87362132, 0.51015805, 0.39585581, 0.13306089],
       [0.72276227, 0.60964058, 0.83963208, 0.68500554]])

In [143]:
arr2 = arr.reshape(4,3)

In [144]:
arr2

array([[0.85086192, 0.5041171 , 0.66829838],
       [0.43191059, 0.87362132, 0.51015805],
       [0.39585581, 0.13306089, 0.72276227],
       [0.60964058, 0.83963208, 0.68500554]])

In [145]:
arr2[1,2]

0.5101580493376978

In [155]:
arr2[1:4,2]

array([0.51015805, 0.72276227, 0.68500554])

In [157]:
arr = np.random.randint(1,100,(5,5))

In [158]:
arr

array([[ 9, 21, 78, 79, 49],
       [12, 49, 81, 14, 20],
       [55, 40, 56, 94, 85],
       [14, 29, 58, 59, 83],
       [41, 98, 12, 99, 43]])

In [159]:
arr>50

array([[False, False,  True,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False,  True, False,  True, False]])

In [160]:
arr[arr>50]

array([78, 79, 81, 55, 56, 94, 85, 58, 59, 83, 98, 99])

In [161]:
arr

array([[ 9, 21, 78, 79, 49],
       [12, 49, 81, 14, 20],
       [55, 40, 56, 94, 85],
       [14, 29, 58, 59, 83],
       [41, 98, 12, 99, 43]])

In [166]:
arr[2:4,1:3]

array([[40, 56],
       [29, 58]])

In [169]:
arr[0,0] = 5000

In [170]:
arr

array([[5000,   21,   78,   79,   49],
       [  12,   49,   81,   14,   20],
       [  55,   40,   56,   94,   85],
       [  14,   29,   58,   59,   83],
       [  41,   98,   12,   99,   43]])

In [171]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [172]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [173]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [174]:
arr1 + arr2

array([[2, 4, 4],
       [3, 2, 3],
       [3, 3, 4]])

In [175]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  0, -1],
       [ 1, -1,  0]])

In [176]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 0.5],
       [2. , 0.5, 1. ]])

In [177]:
arr1 * arr2

array([[1, 4, 4],
       [2, 1, 2],
       [2, 2, 4]])

In [178]:
arr1@arr2

array([[ 7,  8, 10],
       [ 4,  5,  6],
       [ 6,  9, 10]])

In [179]:
arr1/0

/tmp/ipykernel_85/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [180]:
arr1+100

array([[101, 102, 102],
       [101, 101, 101],
       [102, 101, 102]])

In [181]:
arr1**2

array([[1, 4, 4],
       [1, 1, 1],
       [4, 1, 4]])

In [182]:
# Numpy broadcasting

In [183]:
arr = np.zeros((4,4))

In [184]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [185]:
row = np.array([1,2,3,4])

In [186]:
row

array([1, 2, 3, 4])

In [187]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [188]:
row.T

array([1, 2, 3, 4])

In [189]:
col = np.array([[1,2,3,4]])

In [191]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [193]:
arr1 = np.random.randint(1,4,(3,4))

In [194]:
arr1

array([[3, 3, 2, 3],
       [2, 3, 1, 2],
       [1, 1, 3, 2]])

In [195]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.        , 1.41421356],
       [1.        , 1.        , 1.73205081, 1.41421356]])

In [196]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692,  2.71828183,  7.3890561 ],
       [ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ]])

In [197]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.        , 0.30103   ],
       [0.        , 0.        , 0.47712125, 0.30103   ]])